### ISSUE TITLE
[Question] Articulated Config

### ISSUE THREAD

**Issue by WonderLycan** [EtiTheSpirit/ThreeRingsSharp#8]
where can I find an Articulated Config that references an animation?

**Comment by EtiTheSpirit** [comment]
The vast majority of these types reference at least one animation (it's why they are articulated - so they can be animated).

If you want a random example? `rsrc/character/npc/monster/gremlin/null/model.dat` is the one I use for testing all the time.

**Comment by WonderLycan** [comment]
thanks,

**Comment by WonderLycan** [comment]
I am looking forward to see this improve in the near future, good luck.
